(source melpa)

(package-file "ros.el")
(depends-on "s")
(depends-on "hydra")
(depends-on "with-shell-interpreter")
(depends-on "kv")
(depends-on "cl-lib")

(development
 (depends-on "ert")
 (depends-on "flycheck")
 (depends-on "flycheck-cask")
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "cask-package-toolset")
 (depends-on "undercover")
 (depends-on "package-lint"))
