FROM ros:noetic
RUN apt-get update &&\
    apt-get upgrade -y
RUN apt-get -y install python3-colcon-common-extensions python3-catkin-tools git python3-osrf-pycommon && \
    mkdir -p /ws/src &&\
    git clone https://github.com/ros-planning/navigation_tutorials /ws/src/navigation_tutorials &&\
    rosdep install --from-paths /ws/src --ignore-src -ry
RUN /bin/bash -c "cd /ws &&source /opt/ros/noetic/setup.bash && colcon build"
